version: "3.9"
services:
  numbot:
    build:
      context: .
    image: ddrm86/numbot:1.0
    ports:
      - "8080:8080"
    volumes:
      - numbot.sq3:/opt/numbot_db/numbot.sq3
volumes:
  numbot.sq3:
